spring:
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:3307/effective}
    username: ${MYSQL_USERNAME:username}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TIME:1800000}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
