spring:
  datasource:
    url: ${MYSQL_JDBC_URL:jdbc:mysql://localhost:3307/effective}
    username: ${MYSQL_USERNAME:username}
    password: ${MYSQL_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cache:
    redis:
      time-to-live: ${REDIS_TIME:3600000}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
      springframework:
        cache: trace
        orm.jpa.JpaTransactionManager: debug
        security: trace